import { Resend } from "resend";
import { NextRequest, NextResponse } from "next/server";

function formatReportHtml(data: any): string {
  const hasC = data.comps && data.comps.length > 0;
  let tableRows = "";

  if (data.secs) {
    for (const sec of data.secs) {
      tableRows += `<tr><td colspan="${hasC ? data.comps.length + 3 : 4}" style="background:#0a0a0d;padding:8px 12px;font-family:monospace;font-size:11px;color:#666;text-transform:uppercase;letter-spacing:0.1em">${sec.cat}</td></tr>`;
      for (const row of sec.rows || []) {
        if (hasC) {
          const cells = data.comps
            .map(
              (c: string) =>
                `<td style="padding:10px 12px;font-size:13px;border-bottom:1px solid #222">${row.sc?.[c]?.r || "—"}</td>`
            )
            .join("");
          tableRows += `<tr><td style="padding:10px 12px;font-size:11px;color:#666;font-weight:600">${row.dim}</td>${cells}<td style="padding:10px 12px;font-size:12px;color:#8a8a98">${row.ins || ""}</td><td style="padding:10px 12px;font-size:12px;color:#a89ef5">${row.rec || ""}</td></tr>`;
        } else {
          tableRows += `<tr><td style="padding:10px 12px;font-size:11px;color:#666">${row.dim}</td><td style="padding:10px 12px;font-size:12px">${row.find || ""}</td><td style="padding:10px 12px">${row.r || ""}</td><td style="padding:10px 12px;color:#a89ef5">${row.rec || ""}</td></tr>`;
        }
      }
    }
  }

  const headerCells = hasC
    ? `<th style="padding:12px;font-size:10px;color:#e8ff47;text-align:left">${(data.comps || []).join("</th><th style=\"padding:12px;font-size:10px;color:#e8ff47;text-align:left\">")}</th><th style="padding:12px;font-size:10px;color:#7c6dfa">Key Insight</th><th style="padding:12px;font-size:10px;color:#7c6dfa">Your Move</th>`
    : `<th style="padding:12px;font-size:10px">Current Pattern</th><th style="padding:12px;font-size:10px">Rating</th><th style="padding:12px;font-size:10px;color:#7c6dfa">Your Move</th>`;

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>UX Report</title></head>
<body style="margin:0;padding:24px;font-family:system-ui,-apple-system,sans-serif;background:#090909;color:#efefef">
  <div style="max-width:800px;margin:0 auto">
    <h1 style="font-size:24px;margin-bottom:8px">UX Rival Report</h1>
    ${data.headline ? `<p style="font-size:18px;font-weight:700;border-left:3px solid #e8ff47;padding:12px 16px;background:#101012;margin-bottom:16px">${data.headline}</p>` : ""}
    ${data.sum ? `<p style="font-size:14px;color:#b0b0bc;line-height:1.6;margin-bottom:24px"><strong>Overview —</strong> ${data.sum}</p>` : ""}
    <table style="width:100%;border-collapse:collapse;border:1px solid #212126;border-radius:8px;overflow:hidden">
      <thead style="background:#0c0c0e">
        <tr>
          <th style="padding:12px;font-size:10px;color:#666;text-align:left">Dimension</th>
          ${headerCells}
        </tr>
      </thead>
      <tbody>${tableRows}</tbody>
    </table>
    ${data.opp ? `<div style="margin-top:16px;padding:14px 20px;background:rgba(232,255,71,0.07);border-top:1px solid rgba(232,255,71,0.1)"><span style="font-size:9px;color:#e8ff47;letter-spacing:0.1em">GAP</span><p style="margin:4px 0 0;font-size:13px;color:#c8d87a">${data.opp}</p></div>` : ""}
    <p style="margin-top:32px;font-size:11px;color:#3a3a42;font-family:monospace">Generated by UXRival.com — Free AI UX Analysis</p>
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.clone().json();
    console.log("WATCHLIST BODY:", JSON.stringify(body));
    
    const { email, category, competitors, depth, reportData } = body;

    if (!email) {
      console.log("MISSING FIELD: email");
      return NextResponse.json({ error: "email, category, and reportData required" }, { status: 400 });
    }
    if (!category) {
      console.log("MISSING FIELD: category");
      return NextResponse.json({ error: "email, category, and reportData required" }, { status: 400 });
    }
    if (!reportData) {
      console.log("MISSING FIELD: reportData");
      return NextResponse.json({ error: "No report data available. Please run an analysis first, then add to watchlist." }, { status: 400 });
    }

    const resendKey = process.env.RESEND_API_KEY;

    if (!resendKey) return NextResponse.json({ error: "RESEND_API_KEY missing" }, { status: 500 });

    const html = formatReportHtml(reportData);

    const resend = new Resend(resendKey);
    try {
      const data = await resend.emails.send({
        from: "UX Rival <hello@uxrival.xyz>",
        to: email,
        subject: `Your UX Rival Report — ${category}`,
        html,
      });
      console.log("RESEND RESPONSE:", JSON.stringify(data));
      return NextResponse.json({ success: true });
    } catch (error: any) {
      console.log("RESEND ERROR:", JSON.stringify(error));
      return NextResponse.json({ error: error.message || "Failed to send email" }, { status: 500 });
    }
  } catch (err: unknown) {
    console.error("Watchlist send error:", err);
    const msg = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
